version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:delegated     # dev only: monte le code local (supprimer en prod)
      - data:/app/data               # volume nommé pour données persistantes
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ai_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai_frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app:delegated   # dev only: monte le code local (supprimer en prod)
      - data:/app/data
    env_file:
      - .env
    depends_on:
      - backend
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ai_net

volumes:
  data:

networks:
  ai_net:
    driver: bridge